### ISSUE TITLE
Missing confirmation of permission from ZML

### ISSUE THREAD

**Issue by Andre601** [VolmitSoftware/PermissionsEx#10]
On [MCTrades](https://mctrades.org/resources/permissionsex.211/) do you mention that you have the permission of ZML, to distribute this version of PermissionsEx, but there is no clear proof of permission.

If you really have the permission (which I honestly don't believe), then please provide them **visible** on the plugin-page and the GitHub-Repository.
If you don't have permission, then please remove the plugin as fast as possible from the plugin-page, or I have to take action against you by reporting the resource on the site.

Please do not claim anything without a valid proof, because I and some other people have proof for the case, that you don't have permission for distribution.

**Comment by AvianAeternum** [comment]
This isnt an issue, please open issues for actual issues. As for my right to operate this fork, zml's permission was if I wanted to continue to publish pex, as pex, on spigot, however, im not only renaming it after i make considerable contribution and feature changes, but will never publish it to spigot. Irrelevant of whether or not I have permission, pex is open source, and available to all to fork, modify, re purpose or republish under the restraints of its license. And lastly, seriously? This isnt for you guys. This fork is for me. Because I love and support pex, and didnt want it to die, you guys getting access is just a bonus. If you want like, support, and stability, and built for the public, go check out luck perms. Luck is a great guy too. <3
